// ═══ RuangGaya — Central Configuration ═══

export const TEMPLATES = [
  { id: '1x1', label: '1×1 Polaroid', slots: 1, cols: 1, previewImg: '' },
  { id: '2x1', label: '2×1 Duo Strip', slots: 2, cols: 1, previewImg: '' },
  { id: '3x1', label: '3×1 Classic Strip', slots: 3, cols: 1, previewImg: '' },
  { id: '4x1', label: '4×1 Korean Strip', slots: 4, cols: 1, previewImg: '' },
  { id: '1x2', label: '1×2 Wide Duo', slots: 2, cols: 2, previewImg: '' },
  { id: '2x2', label: '2×2 Square Grid', slots: 4, cols: 2, previewImg: '' },
  { id: '2x3', label: '2×3 Story Grid', slots: 6, cols: 2, previewImg: '' },
  { id: '3x2', label: '3×2 Wide Grid', slots: 6, cols: 3, previewImg: '' },
  { id: '4x2', label: '4×2 Party Board', slots: 8, cols: 2, previewImg: '' },
] as const;

export type Template = (typeof TEMPLATES)[number];
export type TemplateId = Template['id'];



// ─────────────────────────────────────────────────────────────────────
//  Frame Configuration
// ─────────────────────────────────────────────────────────────────────

export interface SlotRect {
  x: number;      // percentage 0 - 100
  y: number;      // percentage 0 - 100
  width: number;  // percentage 0 - 100
  height: number; // percentage 0 - 100
}

export interface FrameConfig {
  id: string;
  name: string;
  bgColor: string;
  borderColor: string;
  /** Path ke gambar background (svg/jpg/png). null = tidak ada. */
  bgImage: string | null;
  /** Optional custom slot positions in percentage of canvas */
  customSlots?: SlotRect[];
}

export const FRAMES: FrameConfig[] = [
  // ── Designer SVG Backgrounds (Jepreto signature styles) ────────────
  {
    id: 'bg-newspaper-sal-priadi',
    name: 'Foto Kita Blur (Newspaper)',
    bgColor: '#f8f5ec',
    borderColor: '#221e1a',
    bgImage: '/backgrounds/frame-foto-kita-blur.svg',
    customSlots: [
      { x: 6.25, y: 20.33, width: 45.5, height: 28.33 },
      { x: 6.25, y: 57.33, width: 45.5, height: 28.33 },
    ],
  },
  {
    id: 'bg-couple8',
    name: 'couple8 Monkey Meme',
    bgColor: '#fcfaff',
    borderColor: '#8e36ff',
    bgImage: '/backgrounds/frame-couple8.svg',
    customSlots: [
      { x: 5.5, y: 4, width: 43, height: 22 },
      { x: 5.5, y: 27.5, width: 43, height: 22 },
      { x: 5.5, y: 51, width: 43, height: 22 },
      { x: 5.5, y: 74.5, width: 43, height: 22 },
    ],
  },
  {
    id: 'bg-batik-lumore',
    name: 'Frame Batik 1 (Lumore)',
    bgColor: '#fffdf9',
    borderColor: '#d4af37',
    bgImage: '/backgrounds/frame-batik-1.svg',
    customSlots: [
      { x: 6.5, y: 5, width: 40.5, height: 21 },
      { x: 6.5, y: 28, width: 40.5, height: 21 },
      { x: 6.5, y: 51, width: 40.5, height: 21 },
      { x: 6.5, y: 74, width: 40.5, height: 21 },
      { x: 53, y: 5, width: 40.5, height: 21 },
      { x: 53, y: 28, width: 40.5, height: 21 },
      { x: 53, y: 51, width: 40.5, height: 21 },
      { x: 53, y: 74, width: 40.5, height: 21 },
    ],
  },
  {
    id: 'bg-kk-studio',
    name: 'KK Studio 4r 3',
    bgColor: '#0a1322',
    borderColor: '#ffd166',
    bgImage: '/backgrounds/frame-kk-studio-4r3.svg',
    customSlots: [
      { x: 6.5, y: 5.67, width: 41.5, height: 20.67 },
      { x: 6.5, y: 28.33, width: 41.5, height: 20.67 },
      { x: 6.5, y: 51, width: 41.5, height: 20.67 },
      { x: 6.5, y: 73.67, width: 41.5, height: 20.67 },
      { x: 52, y: 5.67, width: 41.5, height: 20.67 },
      { x: 52, y: 28.33, width: 41.5, height: 20.67 },
      { x: 52, y: 51, width: 41.5, height: 20.67 },
      { x: 52, y: 73.67, width: 41.5, height: 20.67 },
    ],
  },
  {
    id: 'bg-batik1',
    name: 'Nusantara Batik',
    bgColor: '#1B1510',
    borderColor: '#c5a059',
    bgImage: '/backgrounds/bg-batik1.svg',
  },
  {
    id: 'bg-cyber-y2k',
    name: 'Cyber Y2K Matrix',
    bgColor: '#180e29',
    borderColor: '#00f0ff',
    bgImage: '/backgrounds/bg-cyber-y2k.svg',
  },
  {
    id: 'bg-vintage-film',
    name: '35mm Vintage Film',
    bgColor: '#121212',
    borderColor: '#ffd000',
    bgImage: '/backgrounds/bg-vintage-film.svg',
  },
  {
    id: 'bg-korean-ribbon',
    name: 'Coquette Ribbon',
    bgColor: '#fff0f5',
    borderColor: '#ff85b2',
    bgImage: '/backgrounds/bg-korean-ribbon.svg',
  },
  {
    id: 'bg-matcha-latte',
    name: 'Matcha Garden',
    bgColor: '#e3ece1',
    borderColor: '#607955',
    bgImage: '/backgrounds/bg-matcha-latte.svg',
  },
  {
    id: 'bg-cherry-pop',
    name: 'Cherry Pop Gingham',
    bgColor: '#fff1f2',
    borderColor: '#fb7185',
    bgImage: '/backgrounds/bg-cherry-pop.svg',
  },
  {
    id: 'bg-cow-print',
    name: 'Aesthetic Cow Print',
    bgColor: '#fffbf5',
    borderColor: '#242124',
    bgImage: '/backgrounds/bg-cow-print.svg',
  },
  {
    id: 'bg-cloud-dream',
    name: 'Cloudscape Dream',
    bgColor: '#d6e4ff',
    borderColor: '#8e36ff',
    bgImage: '/backgrounds/bg-cloud-dream.svg',
  },
  {
    id: 'bg-acid-barcode',
    name: 'Acid Barcode Pop',
    bgColor: '#d4ff00',
    borderColor: '#202030',
    bgImage: '/backgrounds/bg-acid-barcode.svg',
  },
  {
    id: 'bg-gradient-aura',
    name: 'Dreamy Aura Holo',
    bgColor: '#fce7f3',
    borderColor: '#c084fc',
    bgImage: '/backgrounds/bg-gradient-aura.svg',
  },
  {
    id: 'bg-heart-doodle',
    name: 'Heart Doodles',
    bgColor: '#fff1f2',
    borderColor: '#e11d48',
    bgImage: '/backgrounds/bg-heart-doodle.svg',
  },
  {
    id: 'bg-wavy-retro',
    name: '70s Groovy Waves',
    bgColor: '#fdf6e7',
    borderColor: '#e0663a',
    bgImage: '/backgrounds/bg-wavy-retro.svg',
  },
  {
    id: 'bg-koran',
    name: 'Retro Newspaper',
    bgColor: '#f5efe6',
    borderColor: '#202030',
    bgImage: '/backgrounds/bg-koran.png',
  },
  {
    id: 'bg-spotify1',
    name: 'Spotify Player',
    bgColor: '#121212',
    borderColor: '#1ed760',
    bgImage: '/backgrounds/bg-spotify1.jpg',
  },
  {
    id: 'bg-cat1',
    name: 'Cute Neko 1',
    bgColor: '#eef2ff',
    borderColor: '#818cf8',
    bgImage: '/backgrounds/bg-cat1.jpg',
  },
  {
    id: 'bg-cat2',
    name: 'Mochi Kitten',
    bgColor: '#fdf2f8',
    borderColor: '#f472b6',
    bgImage: '/backgrounds/bg-cat2.jpg',
  },
  {
    id: 'bg-black1',
    name: 'Noir Texture',
    bgColor: '#18181b',
    borderColor: '#52525b',
    bgImage: '/backgrounds/bg-black1.jpg',
  },
  {
    id: 'bg-blue1',
    name: 'Summer Ocean',
    bgColor: '#e0f2fe',
    borderColor: '#38bdf8',
    bgImage: '/backgrounds/bg-blue1.jpg',
  },
  {
    id: 'bg-pink1',
    name: 'Sweet Romantic',
    bgColor: '#fdf2f8',
    borderColor: '#f472b6',
    bgImage: '/backgrounds/bg-pink1.jpg',
  },
  {
    id: 'bg-purple1',
    name: 'Lilac Horizon',
    bgColor: '#f3e8ff',
    borderColor: '#c084fc',
    bgImage: '/backgrounds/bg-purple1.jpg',
  },
  {
    id: 'bg-red1',
    name: 'Red Velvet Pop',
    bgColor: '#fee2e2',
    borderColor: '#f87171',
    bgImage: '/backgrounds/bg-red1.jpg',
  },

  // ── Disney & Pixar Cartoon Cute Frames ───────────────────────────
  {
    id: 'bg-pixar-clouds',
    name: "Toy Story Andy's Sky",
    bgColor: '#38bdf8',
    borderColor: '#f59e0b',
    bgImage: '/backgrounds/bg-pixar-clouds.svg',
  },
  {
    id: 'bg-disney-magic',
    name: 'Disney Fairytale Magic',
    bgColor: '#1e1b4b',
    borderColor: '#facc15',
    bgImage: '/backgrounds/bg-disney-magic.svg',
  },
  {
    id: 'bg-pixar-balloons',
    name: 'Pixar Up Flying Balloons',
    bgColor: '#fed7aa',
    borderColor: '#f97316',
    bgImage: '/backgrounds/bg-pixar-balloons.svg',
  },
  {
    id: 'bg-monsters-inc',
    name: 'Monsters Scream & Doors',
    bgColor: '#06b6d4',
    borderColor: '#84cc16',
    bgImage: '/backgrounds/bg-monsters-inc.svg',
  },
  {
    id: 'bg-stitch-aloha',
    name: 'Stitch Tropical Ohana',
    bgColor: '#0284c7',
    borderColor: '#f43f5e',
    bgImage: '/backgrounds/bg-stitch-aloha.svg',
  },
  {
    id: 'bg-disney-honey',
    name: 'Pooh Bear Sweet Honey',
    bgColor: '#fef3c7',
    borderColor: '#d97706',
    bgImage: '/backgrounds/bg-disney-honey.svg',
  },

  // ── Meme Kocak & Viral Frames ────────────────────────────────────
  {
    id: 'bg-meme-fine',
    name: 'Meme "This Is Fine"',
    bgColor: '#ffedd5',
    borderColor: '#ea580c',
    bgImage: '/backgrounds/bg-meme-fine.svg',
  },
  {
    id: 'bg-meme-doge',
    name: 'Meme Doge "Much Wow"',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    bgImage: '/backgrounds/bg-meme-doge.svg',
  },
  {
    id: 'bg-meme-cat-huh',
    name: 'Meme Cat "Huh?" & Buffering',
    bgColor: '#ede9fe',
    borderColor: '#7c3aed',
    bgImage: '/backgrounds/bg-meme-cat-huh.svg',
  },
  {
    id: 'bg-meme-hamster',
    name: 'Meme Sad Hamster Gwenchana',
    bgColor: '#fff1f2',
    borderColor: '#f43f5e',
    bgImage: '/backgrounds/bg-meme-hamster.svg',
  },
  {
    id: 'bg-meme-sideeye',
    name: 'Meme Bombastic Side-Eye',
    bgColor: '#fef08a',
    borderColor: '#ef4444',
    bgImage: '/backgrounds/bg-meme-sideeye.svg',
  },
  {
    id: 'bg-meme-skull',
    name: "Meme Skull \"I'm Dead\"",
    bgColor: '#090d16',
    borderColor: '#00f0ff',
    bgImage: '/backgrounds/bg-meme-skull.svg',
  },

  // ── Disney & Pixar Batch 2 ───────────────────────────────────────
  {
    id: 'bg-pixar-cars',
    name: 'Cars Lightning McQueen #95',
    bgColor: '#b91c1c',
    borderColor: '#facc15',
    bgImage: '/backgrounds/bg-pixar-cars.svg',
  },
  {
    id: 'bg-pixar-nemo',
    name: 'Finding Nemo Coral Ocean',
    bgColor: '#0284c7',
    borderColor: '#38bdf8',
    bgImage: '/backgrounds/bg-pixar-nemo.svg',
  },
  {
    id: 'bg-pixar-insideout',
    name: 'Inside Out Core Memories',
    bgColor: '#2e1065',
    borderColor: '#facc15',
    bgImage: '/backgrounds/bg-pixar-insideout.svg',
  },
  {
    id: 'bg-pixar-ratatouille',
    name: 'Ratatouille Chef Remy Bistro',
    bgColor: '#fef2f2',
    borderColor: '#dc2626',
    bgImage: '/backgrounds/bg-pixar-ratatouille.svg',
  },
  {
    id: 'bg-disney-frozen',
    name: 'Frozen Elsa Frost & Olaf',
    bgColor: '#e0f2fe',
    borderColor: '#0284c7',
    bgImage: '/backgrounds/bg-disney-frozen.svg',
  },
  {
    id: 'bg-disney-lionking',
    name: 'Lion King Hakuna Matata',
    bgColor: '#c2410c',
    borderColor: '#facc15',
    bgImage: '/backgrounds/bg-disney-lionking.svg',
  },

  // ── Meme Kocak & Viral Batch 2 ───────────────────────────────────
  {
    id: 'bg-meme-capybara',
    name: 'Meme Capybara OK I Pull Up',
    bgColor: '#fef3c7',
    borderColor: '#b45309',
    bgImage: '/backgrounds/bg-meme-capybara.svg',
  },
  {
    id: 'bg-meme-gigachad',
    name: 'Meme GigaChad Mewing 🗿',
    bgColor: '#0f172a',
    borderColor: '#00f0ff',
    bgImage: '/backgrounds/bg-meme-gigachad.svg',
  },
  {
    id: 'bg-meme-spongebob',
    name: 'Meme Mocking SpongeBob 🤪',
    bgColor: '#fef08a',
    borderColor: '#ca8a04',
    bgImage: '/backgrounds/bg-meme-spongebob.svg',
  },
  {
    id: 'bg-meme-chillguy',
    name: 'Meme Just a Chill Guy 🍂',
    bgColor: '#fef3c7',
    borderColor: '#92400e',
    bgImage: '/backgrounds/bg-meme-chillguy.svg',
  },
  {
    id: 'bg-meme-yellingcat',
    name: 'Meme Woman Yelling at Cat 🥗',
    bgColor: '#fff1f2',
    borderColor: '#ef4444',
    bgImage: '/backgrounds/bg-meme-yellingcat.svg',
  },
  {
    id: 'bg-meme-overthinking',
    name: 'Meme 3 AM Overthinking Void 🌀',
    bgColor: '#0f172a',
    borderColor: '#38bdf8',
    bgImage: '/backgrounds/bg-meme-overthinking.svg',
  },

  // ── Solid color minimal frames ───────────────────────────────────
  {
    id: 'white',
    name: 'White Clean',
    bgColor: '#FFFFFF',
    borderColor: '#E8E8E8',
    bgImage: null,
  },
  {
    id: 'black',
    name: 'Classic Black',
    bgColor: '#1A1A1A',
    borderColor: '#333333',
    bgImage: null,
  },
  {
    id: 'butter-yellow',
    name: 'Butter Yellow',
    bgColor: '#FEF9C3',
    borderColor: '#FDE047',
    bgImage: null,
  },
  {
    id: 'sage-green',
    name: 'Sage Green',
    bgColor: '#E2E8DE',
    borderColor: '#A8BFA6',
    bgImage: null,
  },
  {
    id: 'slate-dark',
    name: 'Slate Neo-Dark',
    bgColor: '#202030',
    borderColor: '#8E36FF',
    bgImage: null,
  },
  {
    id: 'pink',
    name: 'Pink Soft',
    bgColor: '#FFF0F5',
    borderColor: '#F4C0D1',
    bgImage: null,
  },
  {
    id: 'dark-pink',
    name: 'Dark Rose',
    bgColor: '#993556',
    borderColor: '#D4537E',
    bgImage: null,
  },
  {
    id: 'lavender',
    name: 'Lavender Mist',
    bgColor: '#F0EAFF',
    borderColor: '#C9B8F0',
    bgImage: null,
  },
  {
    id: 'mint',
    name: 'Mint Fresh',
    bgColor: '#EAFAF4',
    borderColor: '#A8E6CF',
    bgImage: null,
  },
  {
    id: 'nude',
    name: 'Nude Beige',
    bgColor: '#F5EDE0',
    borderColor: '#D4B896',
    bgImage: null,
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue Pastel',
    bgColor: '#E0F2FE',
    borderColor: '#7DD3FC',
    bgImage: null,
  },
  {
    id: 'cherry-red',
    name: 'Cherry Pastel',
    bgColor: '#FEE2E2',
    borderColor: '#FCA5A5',
    bgImage: null,
  },
  {
    id: 'mocha-brown',
    name: 'Mocha Warm',
    bgColor: '#EDE4DC',
    borderColor: '#C4B5A5',
    bgImage: null,
  },
];

export type Frame = FrameConfig;

// ─────────────────────────────────────────────────────────────────────
//  Preset Templates Catalog (Jepreto-style showcase)
// ─────────────────────────────────────────────────────────────────────

export interface PresetTemplate {
  id: string;
  title: string;
  description: string;
  templateId: TemplateId;
  frameId: string;
  category: 'Aesthetic' | 'Retro' | 'Minimal' | 'Cute' | 'Party' | 'Cartoon' | 'Meme';
  uses: number;
  badge?: string;
  tags: string[];
  author: string;
}

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'sal-priadi-blur-2x1',
    title: '3',
    description: 'FOTO KITA BLUR — Newspaper Press edition berpadu lirik Sal Priadi.',
    templateId: '2x1',
    frameId: 'bg-newspaper-sal-priadi',
    category: 'Retro',
    uses: 16947,
    badge: 'Trending',
    tags: ['Koran', 'Newspaper', 'Sal Priadi', 'Blur', 'Aesthetic'],
    author: 'Jepreto Creator',
  },
  {
    id: 'couple8-monkey-4x1',
    title: 'couple8',
    description: 'Pose lucu ekspresif meme monkey couple photostrip viral.',
    templateId: '4x1',
    frameId: 'bg-couple8',
    category: 'Meme',
    uses: 12054,
    badge: 'Viral',
    tags: ['Meme', 'Monkey', 'Couple', 'Chill Guy', 'Viral'],
    author: 'couple8',
  },
  {
    id: 'frame-batik-1-4x2',
    title: 'Frame Batik 1',
    description: 'Frame Batik 1 motif bunga ivory berpadu aksen Lumore otentik.',
    templateId: '4x2',
    frameId: 'bg-batik-lumore',
    category: 'Retro',
    uses: 382,
    badge: 'Heritage',
    tags: ['Batik', 'Lumore', 'Heritage', 'Floral'],
    author: 'Lumore Studio',
  },
  {
    id: 'kk-studio-4r-4x2',
    title: 'KK Studio 4r 3',
    description: 'Estetika renda vintage elegan berpadu bintang emas navy blue.',
    templateId: '4x2',
    frameId: 'bg-kk-studio',
    category: 'Aesthetic',
    uses: 1658,
    badge: 'Popular',
    tags: ['KK Studio', 'Stars', 'Lace', 'Navy', 'Retro'],
    author: 'KK Studio',
  },
  {
    id: 'nusantara-batik-3x1',
    title: 'Nusantara Batik Kawung',
    description: 'Motif batik kawung elegan berpadu aksen emas khas warisan nusantara.',
    templateId: '3x1',
    frameId: 'bg-batik1',
    category: 'Retro',
    uses: 42100,
    badge: 'Popular',
    tags: ['Batik', 'Heritage', 'Indonesia', 'Vintage'],
    author: 'RuangGaya Studio',
  },
  {
    id: 'cyber-y2k-matrix-4x1',
    title: 'Cyber Y2K Star Matrix',
    description: 'Estetika cyber 2000s dengan starbursts neon cyan dan magenta grid.',
    templateId: '4x1',
    frameId: 'bg-cyber-y2k',
    category: 'Retro',
    uses: 48900,
    badge: 'Trending',
    tags: ['Y2K', 'Cyber', 'Star', 'Glitch'],
    author: 'CyberPop Studio',
  },
  {
    id: 'vintage-film-35mm-3x1',
    title: '35mm Analogue Film Reel',
    description: 'Frame film rol 35mm otentik dengan sprocket holes dan kode cetak analog.',
    templateId: '3x1',
    frameId: 'bg-vintage-film',
    category: 'Retro',
    uses: 53400,
    badge: 'Trending',
    tags: ['Film', '35mm', 'Analogue', 'Kodak'],
    author: 'RollFilm Lab',
  },
  {
    id: 'coquette-ribbon-4x1',
    title: 'Korean Coquette Ribbon',
    description: 'Pita pink coquette manis dengan mutiara ala photobooth viral Korea.',
    templateId: '4x1',
    frameId: 'bg-korean-ribbon',
    category: 'Cute',
    uses: 37800,
    badge: 'Hot',
    tags: ['Ribbon', 'Coquette', 'Pink', 'Korean'],
    author: 'Haru Coquette',
  },
  {
    id: 'matcha-daisy-2x2',
    title: 'Matcha Daisy Garden',
    description: 'Warna sage matcha menenangkan berhias bunga daisy musim semi.',
    templateId: '2x2',
    frameId: 'bg-matcha-latte',
    category: 'Aesthetic',
    uses: 29300,
    badge: 'Popular',
    tags: ['Matcha', 'Daisy', 'Green', 'Pastel'],
    author: 'Matcha Club',
  },
  {
    id: 'cherry-gingham-2x2',
    title: 'Cherry Pop Gingham',
    description: 'Pola gingham pastel berpadu buah ceri merah ceria ala piknik musim panas.',
    templateId: '2x2',
    frameId: 'bg-cherry-pop',
    category: 'Cute',
    uses: 31200,
    badge: 'Cute',
    tags: ['Cherry', 'Gingham', 'Sweet', 'Pastel'],
    author: 'Picnic Day',
  },
  {
    id: 'y2k-cow-print-4x1',
    title: 'Y2K Aesthetic Cow Print',
    description: 'Motif cow spots estetik dengan sentuhan pita pink yang playful dan edgy.',
    templateId: '4x1',
    frameId: 'bg-cow-print',
    category: 'Cute',
    uses: 34600,
    badge: 'Hot',
    tags: ['Cow Print', 'Y2K', 'Animal', 'Aesthetic'],
    author: 'Mood Studio',
  },
  {
    id: 'acid-barcode-party-2x2',
    title: 'Neo-Brutal Acid Barcode',
    description: 'Desain neo-brutalist khas Jepreto dengan acid lime kontras tinggi dan barcode.',
    templateId: '2x2',
    frameId: 'bg-acid-barcode',
    category: 'Party',
    uses: 24500,
    badge: 'Hot',
    tags: ['Acid', 'Neo-Brutal', 'Jepreto', 'Party'],
    author: 'Acid Rave',
  },
  {
    id: 'cloudscape-dream-3x1',
    title: 'Pastel Cloudscape Dream',
    description: 'Gradasi langit pastel lembut dengan awan putih dan kilauan bintang.',
    templateId: '3x1',
    frameId: 'bg-cloud-dream',
    category: 'Aesthetic',
    uses: 26700,
    badge: 'Soft',
    tags: ['Cloud', 'Sky', 'Dream', 'Sparkle'],
    author: 'Skyline Art',
  },
  {
    id: 'dreamy-aura-3x1',
    title: 'Holographic Dreamy Aura',
    description: 'Aura gradient holografik memikat dengan perpaduan peach, lavender, dan mint.',
    templateId: '3x1',
    frameId: 'bg-gradient-aura',
    category: 'Aesthetic',
    uses: 39500,
    badge: 'Popular',
    tags: ['Aura', 'Hologram', 'Gradient', 'Vibe'],
    author: 'Aura Studio',
  },
  {
    id: 'heart-doodle-4x1',
    title: 'Sweet Heart Doodles',
    description: 'Doodle hati gambaran tangan yang imut dan ekspresif di setiap sudut foto.',
    templateId: '4x1',
    frameId: 'bg-heart-doodle',
    category: 'Cute',
    uses: 27800,
    badge: 'Cute',
    tags: ['Heart', 'Doodle', 'Cute', 'Love'],
    author: 'Doodle Art',
  },
  {
    id: 'groovy-wavy-3x1',
    title: '70s Groovy Sunset Waves',
    description: 'Garis gelombang retro 70-an bernuansa terakota, mustard, dan sunset.',
    templateId: '3x1',
    frameId: 'bg-wavy-retro',
    category: 'Retro',
    uses: 22300,
    badge: 'Retro',
    tags: ['70s', 'Groovy', 'Sunset', 'Wavy'],
    author: 'Sunset Retro',
  },
  {
    id: 'y2k-newspaper-4x1',
    title: 'Y2K Retro Daily Press',
    description: 'Format koran vintage retro kekinian yang lagi trending di media sosial.',
    templateId: '4x1',
    frameId: 'bg-koran',
    category: 'Retro',
    uses: 46200,
    badge: 'Trending',
    tags: ['Koran', 'Newspaper', 'Vintage', 'Press'],
    author: 'Retro Gazette',
  },
  {
    id: 'spotify-music-3x1',
    title: 'Spotify Hits Now Playing',
    description: 'Nuansa pemutar musik Spotify dengan progress bar dan metadata lagu favorit.',
    templateId: '3x1',
    frameId: 'bg-spotify1',
    category: 'Aesthetic',
    uses: 51300,
    badge: 'Hot',
    tags: ['Spotify', 'Music', 'Playlist', 'Vibe'],
    author: 'Soundtrack Life',
  },
  {
    id: 'couple-pink-3x1',
    title: 'Romantic Couple Story',
    description: 'Template romantis dengan nuansa pink manis untuk momen berdua.',
    templateId: '3x1',
    frameId: 'bg-pink1',
    category: 'Aesthetic',
    uses: 28900,
    badge: 'Popular',
    tags: ['Couple', 'Pink', 'Romantic', 'Love'],
    author: 'Lovebird Studio',
  },
  {
    id: 'cute-cat-2x2',
    title: 'Neko Diary 2×2',
    description: 'Desain kucing menggemaskan dengan grid 4 foto yang ceria.',
    templateId: '2x2',
    frameId: 'bg-cat1',
    category: 'Cute',
    uses: 25100,
    badge: 'Cute',
    tags: ['Cat', 'Neko', 'Cute', 'Animals'],
    author: 'Neko House',
  },
  {
    id: 'mochi-cat-4x1',
    title: 'Mochi Kitty 4-Strip',
    description: 'Ilustrasi kucing kawaii dengan 4 frame foto memanjang bernuansa pastel.',
    templateId: '4x1',
    frameId: 'bg-cat2',
    category: 'Cute',
    uses: 21400,
    badge: 'Cute',
    tags: ['Mochi', 'Cat', 'Kawaii', 'Pastel'],
    author: 'Kalsa Studio',
  },
  {
    id: 'monochrome-classic-4x1',
    title: 'Seoul Monochrome Classic',
    description: 'Hitam elegan abadi dengan estetika minimalis photobooth Korea.',
    templateId: '4x1',
    frameId: 'black',
    category: 'Minimal',
    uses: 62800,
    badge: 'Classic',
    tags: ['Black & White', 'Minimalist', 'Seoul', 'Clean'],
    author: 'Polar Photobooth',
  },
  {
    id: 'clean-white-polaroid-1x1',
    title: 'Clean White Polaroid',
    description: 'Format polaroid 1-shot murni dengan ruang tanda tangan di bawah foto.',
    templateId: '1x1',
    frameId: 'white',
    category: 'Minimal',
    uses: 19400,
    badge: 'Minimal',
    tags: ['Polaroid', 'Clean', 'White', '1-Shot'],
    author: 'Clean Snap',
  },
  {
    id: 'minimal-duo-2x1',
    title: 'Minimal Duo 2-Strip',
    description: 'Duo foto vertikal bersih tanpa distraksi untuk hasil foto murni dan tajam.',
    templateId: '2x1',
    frameId: 'white',
    category: 'Minimal',
    uses: 14800,
    badge: 'Minimal',
    tags: ['Minimal', 'Duo', 'Clean', 'White'],
    author: 'Pure Frame',
  },
  {
    id: 'wide-duo-matcha-1x2',
    title: 'Matcha Duo Landscape',
    description: 'Format lanskap 2 foto berjajar dengan latar matcha daisy segar.',
    templateId: '1x2',
    frameId: 'bg-matcha-latte',
    category: 'Aesthetic',
    uses: 12600,
    badge: 'New',
    tags: ['Wide', 'Duo', 'Matcha', 'Horizontal'],
    author: 'Matcha Club',
  },
  {
    id: 'cinema-wide-film-3x2',
    title: 'Cinema 6-Reel Wide Film',
    description: 'Tata letak lanskap lebar 6 foto berbingkai klise rol film bioskop.',
    templateId: '3x2',
    frameId: 'bg-vintage-film',
    category: 'Retro',
    uses: 33100,
    badge: 'New',
    tags: ['Cinema', 'Wide', 'Film', 'Reel'],
    author: 'Cinema Reel',
  },
  {
    id: 'mega-party-board-4x2',
    title: '8-Shot Mega Party Board',
    description: 'Papan 8 foto berenergi tinggi untuk seru-seruan bareng geng dan teman nongkrong.',
    templateId: '4x2',
    frameId: 'bg-acid-barcode',
    category: 'Party',
    uses: 29800,
    badge: 'Party',
    tags: ['Mega', 'Party', '8-Shot', 'Group'],
    author: 'Party Mania',
  },
  {
    id: 'red-velvet-party-2x3',
    title: 'Red Velvet 6-Grid Pop',
    description: 'Grid 6 foto penuh energi dan keceriaan pesta bersama teman-teman.',
    templateId: '2x3',
    frameId: 'bg-red1',
    category: 'Party',
    uses: 35400,
    badge: 'Party',
    tags: ['Red', 'Party', 'Grid', 'Pop'],
    author: 'Wijana Studio',
  },
  {
    id: 'butter-yellow-duo-2x1',
    title: 'Butter Yellow Warm Duo',
    description: 'Warna kuning mentega lembut yang hangat untuk potret natural bernuansa cerah.',
    templateId: '2x1',
    frameId: 'butter-yellow',
    category: 'Minimal',
    uses: 11500,
    badge: 'Soft',
    tags: ['Butter', 'Yellow', 'Warm', 'Soft'],
    author: 'Honey Butter',
  },
  {
    id: 'midnight-noir-3x1',
    title: 'Midnight Street Noir',
    description: 'Nuansa gelap bertekstur untuk pose misterius, dramatis, dan artsy.',
    templateId: '3x1',
    frameId: 'bg-black1',
    category: 'Retro',
    uses: 32500,
    badge: 'Popular',
    tags: ['Dark', 'Noir', 'Street', 'Shadow'],
    author: 'Graperan',
  },
  {
    id: 'purple-sunset-2x2',
    title: 'Sunset Lilac Horizon',
    description: 'Gradasi ungu estetik dengan tata letak 2×2 yang serasi.',
    templateId: '2x2',
    frameId: 'bg-purple1',
    category: 'Aesthetic',
    uses: 23400,
    badge: 'Popular',
    tags: ['Sunset', 'Lilac', 'Purple', 'Aesthetic'],
    author: 'Enzy Studio',
  },
  {
    id: 'summer-ocean-3x1',
    title: 'Summer Ocean Wave',
    description: 'Warna biru laut segar untuk abadikan liburan & momen tak terlupakan.',
    templateId: '3x1',
    frameId: 'bg-blue1',
    category: 'Aesthetic',
    uses: 17600,
    badge: 'Fresh',
    tags: ['Summer', 'Ocean', 'Blue', 'Sea'],
    author: 'Sejiwa Booth',
  },
  {
    id: 'coquette-ribbon-2x2',
    title: 'Coquette Bow Square Grid',
    description: 'Tata letak 4 foto bujur sangkar dengan bingkai pita pink dan pearl accent.',
    templateId: '2x2',
    frameId: 'bg-korean-ribbon',
    category: 'Cute',
    uses: 24700,
    badge: 'Cute',
    tags: ['Ribbon', 'Bow', 'Pink', 'Square'],
    author: 'Haru Coquette',
  },
  {
    id: 'acid-rave-strip-4x1',
    title: 'Acid Rave Cyber Strip',
    description: 'Kombinasi 4-strip vertikal bernuansa neo-brutalist acid lime dan stiker grafis.',
    templateId: '4x1',
    frameId: 'bg-acid-barcode',
    category: 'Party',
    uses: 28200,
    badge: 'Hot',
    tags: ['Acid', 'Rave', 'Neon', 'Party'],
    author: 'Acid Rave',
  },

  // ── Disney & Pixar Cartoon Presets ───────────────────────────────
  {
    id: 'toystory-clouds-4x1',
    title: "Toy Story Andy's Sky",
    description: 'Awan ikonik kamar Andy berpadu lencana sheriff Woody dan Pixar ball ceria.',
    templateId: '4x1',
    frameId: 'bg-pixar-clouds',
    category: 'Cartoon',
    uses: 68400,
    badge: 'Hot',
    tags: ['Disney', 'Pixar', 'Toy Story', 'Clouds', 'Cartoon', 'Woody'],
    author: 'Pixar Animation',
  },
  {
    id: 'disney-magic-3x1',
    title: 'Disney Fairytale Kingdom',
    description: 'Kastil megah Cinderella berhias gemerlap bintang dan debu peri magis.',
    templateId: '3x1',
    frameId: 'bg-disney-magic',
    category: 'Cartoon',
    uses: 74200,
    badge: 'Popular',
    tags: ['Disney', 'Castle', 'Magic', 'Princess', 'Fairytale', 'Cartoon'],
    author: 'Magic Kingdom',
  },
  {
    id: 'pixar-up-balloons-2x2',
    title: 'Pixar Up Flying Balloons',
    description: 'Kumpulan balon warna-warni ceria dengan pin pramuka penjelajah alam Carl & Ellie.',
    templateId: '2x2',
    frameId: 'bg-pixar-balloons',
    category: 'Cartoon',
    uses: 56300,
    badge: 'Cute',
    tags: ['Pixar', 'Up', 'Balloons', 'Adventure', 'Cartoon'],
    author: 'Pixar Animation',
  },
  {
    id: 'monsters-inc-4x1',
    title: 'Monsters Scream & Doors',
    description: 'Motif bulu toska Sulley & Mike Wazowski lengkap dengan tabung energi tawa.',
    templateId: '4x1',
    frameId: 'bg-monsters-inc',
    category: 'Cartoon',
    uses: 48900,
    badge: 'Trending',
    tags: ['Monsters Inc', 'Pixar', 'Mike', 'Sulley', 'Doors', 'Cartoon'],
    author: 'Monstropolis',
  },
  {
    id: 'stitch-ohana-3x1',
    title: 'Stitch Hawaiian Ohana',
    description: 'Nuansa tropis pantai Hawaii dengan bunga kembang sepatu dan jejak kaki Stitch.',
    templateId: '3x1',
    frameId: 'bg-stitch-aloha',
    category: 'Cartoon',
    uses: 62700,
    badge: 'Cute',
    tags: ['Disney', 'Stitch', 'Aloha', 'Tropical', 'Hawaii', 'Cartoon'],
    author: 'Ohana Island',
  },
  {
    id: 'winnie-honey-2x2',
    title: 'Pooh Bear Sweet Honey',
    description: 'Lelehan madu manis keemasan berhias lebah lucu dan pot madu hangat.',
    templateId: '2x2',
    frameId: 'bg-disney-honey',
    category: 'Cartoon',
    uses: 41500,
    badge: 'Cute',
    tags: ['Disney', 'Pooh', 'Honey', 'Pastel', 'Cartoon', 'Bees'],
    author: 'Hundred Acre Wood',
  },

  // ── Meme Kocak Presets ───────────────────────────────────────────
  {
    id: 'meme-this-is-fine-4x1',
    title: 'Meme "This Is Fine" Dog',
    description: 'Anjing santai ngopi di tengah kobaran api — pas buat pose pura-pura tenang!',
    templateId: '4x1',
    frameId: 'bg-meme-fine',
    category: 'Meme',
    uses: 82100,
    badge: 'Viral',
    tags: ['Meme', 'This Is Fine', 'Dog', 'Funny', 'Kocak', 'Fire'],
    author: 'Meme Lord Studio',
  },
  {
    id: 'meme-doge-much-wow-3x1',
    title: 'Meme Doge "Much Wow"',
    description: 'Teks Comic Sans legendaris Doge shiba inu: such gaya, very photogenic, amaze!',
    templateId: '3x1',
    frameId: 'bg-meme-doge',
    category: 'Meme',
    uses: 89400,
    badge: 'Viral',
    tags: ['Meme', 'Doge', 'Much Wow', 'Shiba', 'Kocak', 'Bonk'],
    author: 'Doge Master',
  },
  {
    id: 'meme-cat-huh-2x2',
    title: 'Meme Cat "Huh?" & Buffering',
    description: 'Muka kucing cengo melongo dengan popup error sistem dan loading otak 1%.',
    templateId: '2x2',
    frameId: 'bg-meme-cat-huh',
    category: 'Meme',
    uses: 67800,
    badge: 'Trending',
    tags: ['Meme', 'Cat', 'Huh', 'Error', 'Buffering', 'Kocak'],
    author: 'Cat Memes Hub',
  },
  {
    id: 'meme-hamster-gwenchana-4x1',
    title: 'Meme Sad Hamster Gwenchana',
    description: 'Hamster mata bulet berkaca-kaca main biola sedih: Gwenchana ding-ding-ding!',
    templateId: '4x1',
    frameId: 'bg-meme-hamster',
    category: 'Meme',
    uses: 79300,
    badge: 'Viral',
    tags: ['Meme', 'Hamster', 'Gwenchana', 'Sad', 'Cute', 'Violin'],
    author: 'Gwenchana Vibe',
  },
  {
    id: 'meme-side-eye-3x1',
    title: 'Meme Bombastic Side-Eye',
    description: 'Tatapan melirik dramatis penuh penghakiman + popcat mulut mangap :O.',
    templateId: '3x1',
    frameId: 'bg-meme-sideeye',
    category: 'Meme',
    uses: 61500,
    badge: 'Hot',
    tags: ['Meme', 'Side Eye', 'Popcat', 'Aura', 'Kocak', 'Criminal'],
    author: 'Bombastic Lab',
  },
  {
    id: 'meme-skull-dead-4x1',
    title: 'Meme Skull "I\'m Dead" FR FR',
    description: 'Doodle tengkorak neon cyber untuk pose ketawa ngakak sampai lemas tanpa tandingan.',
    templateId: '4x1',
    frameId: 'bg-meme-skull',
    category: 'Meme',
    uses: 54600,
    badge: 'Hot',
    tags: ['Meme', 'Skull', 'Dead', 'No Cap', 'Kocak', 'Gen Z'],
    author: 'No Cap Studio',
  },

  // ── Batch 2 Presets ──────────────────────────────────────────────
  {
    id: 'cars-mcqueen-3x1',
    title: 'Cars Lightning McQueen #95',
    description: 'Aksen garis bendera balap, petir emas #95, dan semangat Ka-Chow sang juara Piston Cup!',
    templateId: '3x1',
    frameId: 'bg-pixar-cars',
    category: 'Cartoon',
    uses: 72100,
    badge: 'Popular',
    tags: ['Disney', 'Pixar', 'Cars', 'McQueen', 'Speed', 'Ka-Chow'],
    author: 'Radiator Springs',
  },
  {
    id: 'nemo-dory-4x1',
    title: 'Finding Nemo & Dory Ocean',
    description: 'Terumbu karang bawah laut tropis nan memikat dengan gelembung air dan ikan badut.',
    templateId: '4x1',
    frameId: 'bg-pixar-nemo',
    category: 'Cartoon',
    uses: 64900,
    badge: 'Cute',
    tags: ['Disney', 'Pixar', 'Nemo', 'Dory', 'Ocean', 'Fish'],
    author: 'Great Barrier Reef',
  },
  {
    id: 'insideout-core-2x2',
    title: 'Inside Out Core Memories',
    description: 'Bola memori emosi bercahaya warna-warni yang abadikan setiap tawa dan haru.',
    templateId: '2x2',
    frameId: 'bg-pixar-insideout',
    category: 'Cartoon',
    uses: 59300,
    badge: 'Hot',
    tags: ['Disney', 'Pixar', 'Inside Out', 'Memories', 'Joy'],
    author: 'Headquarters Lab',
  },
  {
    id: 'ratatouille-bistro-3x1',
    title: 'Ratatouille Chef Remy Paris',
    description: 'Nuansa bistro Paris hangat dengan topi koki bertelinga tikus dan keju lezat.',
    templateId: '3x1',
    frameId: 'bg-pixar-ratatouille',
    category: 'Cartoon',
    uses: 47800,
    badge: 'Cute',
    tags: ['Disney', 'Pixar', 'Ratatouille', 'Remy', 'Paris', 'Cooking'],
    author: 'Gusteau Kitchen',
  },
  {
    id: 'frozen-olaf-4x1',
    title: 'Frozen Elsa & Olaf Snowflakes',
    description: 'Kristal salju beku berkilauan di langit biru es bersama Olaf si manusia salju.',
    templateId: '4x1',
    frameId: 'bg-disney-frozen',
    category: 'Cartoon',
    uses: 69400,
    badge: 'Popular',
    tags: ['Disney', 'Frozen', 'Elsa', 'Olaf', 'Snow', 'Winter'],
    author: 'Arendelle Castle',
  },
  {
    id: 'lionking-sunset-2x2',
    title: 'Lion King Hakuna Matata',
    description: 'Cahaya keemasan matahari terbenam savannah Afrika dengan sketsa legendaris Simba.',
    templateId: '2x2',
    frameId: 'bg-disney-lionking',
    category: 'Cartoon',
    uses: 53200,
    badge: 'Classic',
    tags: ['Disney', 'Lion King', 'Simba', 'Sunset', 'Africa'],
    author: 'Pride Lands',
  },
  {
    id: 'meme-capybara-pullup-4x1',
    title: 'Meme Capybara "OK I Pull Up"',
    description: 'Si paling tenang tanpa drama mandi air hangat dengan jeruk mandarin di kepala.',
    templateId: '4x1',
    frameId: 'bg-meme-capybara',
    category: 'Meme',
    uses: 88700,
    badge: 'Viral',
    tags: ['Meme', 'Capybara', 'Pull Up', 'Chill', 'Orange', 'Kocak'],
    author: 'Capy Club',
  },
  {
    id: 'meme-gigachad-mewing-3x1',
    title: 'Meme GigaChad Mewing 🗿',
    description: 'Aura sigma garis keras dengan Moai berkacamata hitam dan rekor mewing tak terputus.',
    templateId: '3x1',
    frameId: 'bg-meme-gigachad',
    category: 'Meme',
    uses: 76500,
    badge: 'Trending',
    tags: ['Meme', 'GigaChad', 'Mewing', 'Sigma', 'Moai', 'Kocak'],
    author: 'Sigma Phonk',
  },
  {
    id: 'meme-spongebob-mock-2x2',
    title: 'Meme Mocking SpongeBob 🤪',
    description: 'Gaya ayam konyol dengan teks huruf besar-kecil ganjil yang cocok untuk ngeledek teman.',
    templateId: '2x2',
    frameId: 'bg-meme-spongebob',
    category: 'Meme',
    uses: 83200,
    badge: 'Viral',
    tags: ['Meme', 'SpongeBob', 'Mocking', 'Rainbow', 'Kocak', 'Funny'],
    author: 'Bikini Bottom Memes',
  },
  {
    id: 'meme-chill-guy-4x1',
    title: 'Meme Just a Chill Guy 🍂',
    description: 'Anjing sweater cokelat tangan di kantong yang santai dan lowkey nggak mikirin masalah.',
    templateId: '4x1',
    frameId: 'bg-meme-chillguy',
    category: 'Meme',
    uses: 94100,
    badge: 'Viral',
    tags: ['Meme', 'Chill Guy', 'Sweater', 'Santai', 'Viral', 'Kocak'],
    author: 'Chill Guy Studio',
  },
  {
    id: 'meme-yelling-cat-3x1',
    title: 'Woman Yelling at Cat Smudge 🥗',
    description: 'Pertarungan emosional antara emak-emak teriak histeris vs kucing cuek makan salad.',
    templateId: '3x1',
    frameId: 'bg-meme-yellingcat',
    category: 'Meme',
    uses: 71800,
    badge: 'Classic',
    tags: ['Meme', 'Smudge', 'Cat', 'Yelling', 'Salad', 'Kocak'],
    author: 'Drama Memes',
  },
  {
    id: 'meme-overthinking-3am-4x1',
    title: 'Meme 3 AM Overthinking Void 🌀',
    description: 'Jam 3 pagi menatap langit kamar sambil mikirin cicak, semut, dan momen memalukan.',
    templateId: '4x1',
    frameId: 'bg-meme-overthinking',
    category: 'Meme',
    uses: 68900,
    badge: 'Trending',
    tags: ['Meme', '3 AM', 'Overthinking', 'Void', 'Cat', 'Relatable'],
    author: 'Insomnia Club',
  },
];

export function getPresetById(id: string): PresetTemplate | undefined {
  return PRESET_TEMPLATES.find((p) => p.id === id);
}

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getFrameById(id: string): Frame | undefined {
  return FRAMES.find((f) => f.id === id);
}


export const FILTERS = [
  'Normal',
  'B&W',
  'Vintage',
  'Vivid',
  'Pastel',
  'Warm',
  'Cyberpunk',
  'Cold Blue',
  'Film Noir',
  'Golden Hour',
  'Soft Glow',
  'Retro 90s',
  'Emerald',
  'Dramatic',
  'Faded Film',
] as const;
export type FilterType = (typeof FILTERS)[number];

export interface FilterMeta {
  id: FilterType;
  label: string;
  icon: string;
  description: string;
  previewBg: string;
}

export const FILTER_METAS: FilterMeta[] = [
  { id: 'Normal',      label: 'Normal',      icon: '✨', description: 'Warna asli kamera',            previewBg: 'linear-gradient(135deg, #cbd5e1, #f8fafc)' },
  { id: 'B&W',         label: 'B&W',         icon: '🖤', description: 'Monokrom klasik hitam putih', previewBg: 'linear-gradient(135deg, #1e293b, #94a3b8)' },
  { id: 'Vintage',     label: 'Vintage',     icon: '🎞️', description: 'Nuansa sepia hangat jadul',   previewBg: 'linear-gradient(135deg, #b45309, #fde68a)' },
  { id: 'Vivid',       label: 'Vivid',       icon: '🌈', description: 'Warna kontras & ekstra pop',  previewBg: 'linear-gradient(135deg, #ec4899, #06b6d4)' },
  { id: 'Pastel',      label: 'Pastel',      icon: '🌸', description: 'Tone lembut & dreamy Korea',   previewBg: 'linear-gradient(135deg, #fbcfe8, #e0e7ff)' },
  { id: 'Warm',        label: 'Warm',        icon: '☕', description: 'Hangat cozy golden glow',     previewBg: 'linear-gradient(135deg, #f97316, #fef08a)' },
  { id: 'Cyberpunk',   label: 'Cyberpunk',   icon: '⚡', description: 'Futuristik neon magenta-cyan', previewBg: 'linear-gradient(135deg, #a855f7, #06b6d4)' },
  { id: 'Cold Blue',   label: 'Cold Blue',   icon: '❄️', description: 'Tone dingin sejuk modern',    previewBg: 'linear-gradient(135deg, #0284c7, #93c5fd)' },
  { id: 'Film Noir',   label: 'Film Noir',   icon: '🎬', description: 'B&W sinematik kontras tinggi',previewBg: 'linear-gradient(135deg, #09090b, #52525b)' },
  { id: 'Golden Hour', label: 'Golden Hour', icon: '🌅', description: 'Cahaya keemasan senja hangat',previewBg: 'linear-gradient(135deg, #ea580c, #fbbf24)' },
  { id: 'Soft Glow',   label: 'Soft Glow',   icon: '💫', description: 'Kulit glowing bersinar lembut',previewBg: 'linear-gradient(135deg, #fda4af, #fef9c3)' },
  { id: 'Retro 90s',   label: 'Retro 90s',   icon: '📼', description: 'Efek kamera VHS tahun 90-an', previewBg: 'linear-gradient(135deg, #d97706, #a1a1aa)' },
  { id: 'Emerald',     label: 'Emerald',     icon: '🍃', description: 'Nuansa alam hijau segar',      previewBg: 'linear-gradient(135deg, #059669, #a7f3d0)' },
  { id: 'Dramatic',    label: 'Dramatic',    icon: '🎭', description: 'Kontras mendalam & tajam',    previewBg: 'linear-gradient(135deg, #1e1b4b, #e11d48)' },
  { id: 'Faded Film',  label: 'Faded Film',  icon: '📷', description: 'Matte pudar khas rol film',   previewBg: 'linear-gradient(135deg, #78716c, #e7e5e4)' },
];

/** Map filter name → CSS filter string */
export const FILTER_CSS: Record<FilterType, string> = {
  Normal: 'none',
  'B&W': 'grayscale(100%)',
  Vintage: 'sepia(60%) contrast(90%) brightness(90%)',
  Vivid: 'saturate(180%) contrast(110%)',
  Pastel: 'saturate(60%) brightness(110%)',
  Warm: 'sepia(30%) saturate(140%) brightness(105%)',
  Cyberpunk: 'hue-rotate(280deg) saturate(190%) contrast(115%)',
  'Cold Blue': 'sepia(20%) hue-rotate(180deg) saturate(130%) brightness(105%)',
  'Film Noir': 'grayscale(100%) contrast(160%) brightness(92%)',
  'Golden Hour': 'sepia(45%) saturate(165%) hue-rotate(-15deg) contrast(105%)',
  'Soft Glow': 'contrast(92%) brightness(112%) saturate(125%)',
  'Retro 90s': 'contrast(88%) brightness(108%) sepia(25%) saturate(135%)',
  Emerald: 'hue-rotate(55deg) saturate(130%) contrast(105%)',
  Dramatic: 'contrast(140%) brightness(95%) saturate(120%)',
  'Faded Film': 'contrast(82%) brightness(115%) saturate(85%) sepia(15%)',
};

export const TIMER_OPTIONS = [3, 5, 10] as const;
export type TimerOption = (typeof TIMER_OPTIONS)[number];

export interface StickerItem {
  id: string;
  src: string;
  width: number;
  height: number;
  transform: string; // CSS transform string (translate, rotate)
}

// ─────────────────────────────────────────────────────────────────────
//  Font & Text Customization
// ─────────────────────────────────────────────────────────────────────

export const FONTS = [
  { id: 'Nunito',           label: 'Friendly',    cssFamily: "'Nunito', sans-serif" },
  { id: 'Playfair Display', label: 'Elegant',     cssFamily: "'Playfair Display', serif" },
  { id: 'Pacifico',         label: 'Playful',     cssFamily: "'Pacifico', cursive" },
  { id: 'Courier Prime',    label: 'Retro',       cssFamily: "'Courier Prime', monospace" },
  { id: 'Outfit',           label: 'Modern',      cssFamily: "'Outfit', sans-serif" },
  { id: 'Dancing Script',   label: 'Handwriting', cssFamily: "'Dancing Script', cursive" },
] as const;

export type FontOption = (typeof FONTS)[number];

export const FONT_SIZES = [16, 18, 20, 22, 26, 30, 36] as const;
export type FontSize = (typeof FONT_SIZES)[number];

export type TextPosition = 'top' | 'bottom';

// ─────────────────────────────────────────────────────────────────────
//  Face Filters
// ─────────────────────────────────────────────────────────────────────

export const FACE_FILTERS = [
  { id: 'none',          label: 'Normal',       icon: '😐', description: 'Tanpa filter wajah' },
  { id: 'cat',           label: 'Cat',          icon: '🐱', description: 'Telinga & kumis kucing lucu' },
  { id: 'dog',           label: 'Dog',          icon: '🐶', description: 'Telinga & lidah anjing gemas' },
  { id: 'glasses',       label: 'Glasses',      icon: '👓', description: 'Kacamata stylish modern' },
  { id: 'crown',         label: 'Crown',        icon: '👑', description: 'Mahkota emas kerajaan & permata' },
  { id: 'flower-crown',  label: 'Flowers',      icon: '🌸', description: 'Mahkota bunga sakura musim semi' },
  { id: 'butterfly',     label: 'Butterfly',    icon: '🦋', description: 'Sayap kupu-kupu ungu gradasi' },
  { id: 'clown',         label: 'Clown',        icon: '🤡', description: 'Hidung badut merah ceria' },
  { id: 'sparkle',       label: 'Sparkle',      icon: '✨', description: 'Glitter & bintang gemerlap' },
  { id: 'beauty',        label: 'Beauty',       icon: '💄', description: 'Efek kulit halus & glowing cerah' },
  { id: 'devil',         label: 'Devil',        icon: '😈', description: 'Tanduk merah neon & aura iblis imut' },
  { id: 'angel',         label: 'Angel',        icon: '😇', description: 'Halo emas melayang & kilau malaikat' },
  { id: 'bunny',         label: 'Bunny',        icon: '🐰', description: 'Telinga kelinci panjang & hidung pink' },
  { id: 'pixel-glasses', label: 'Thug Life',    icon: '😎', description: 'Kacamata pixel hitam 8-bit retro' },
  { id: 'heart-blush',   label: 'Heart Blush',  icon: '💕', description: 'Pipi love merah merona & hati melayang' },
  { id: 'cyber-visor',   label: 'Cyber Visor',  icon: '🤖', description: 'Kacamata visor neon sci-fi futuristik' },
  { id: 'mustache',      label: 'Gentleman',    icon: '🥸', description: 'Kumis klasik vintage & kacamata retro' },
  { id: 'star-eyes',     label: 'Star Eyes',    icon: '🤩', description: 'Mata bintang berputar & freckles' },
  { id: 'flower-blush',  label: 'Daisy Cheek',  icon: '🌼', description: 'Bunga daisy ceria di pipi & hidung' },
] as const;

export type FaceFilterId = (typeof FACE_FILTERS)[number]['id'];

